server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students,/api/students/**
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/courses,/api/courses/**
        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/api/enrollments,/api/enrollments/**

eureka:
  client:
    service-url:
      defaultZone: http://10.128.0.58:8761/eureka/
